language: node_js
os:
- linux
- osx
node_js:
- 4
- 6
- stable
before_install:
- npm i npm@latest -g
deploy:
  provider: npm
  on:
    tags: true
  email:
    secure: lIzbgihraAoyJgnfVifaO0E/tRDeXSoH8f8NDzgMwxPdncaNwJF/NW/mMYgub1rO6DiX4a+uxf4rott+ObW8x0JxgVO0t23KvYeT8rnUWXStUjD2INW5z8lLKgqLi7Um7/4H6emwHsf2A9vJlt/n8BHVfjTxGOqeqm+UxsWi0Ylr6T5vihDksCkleCYGlpayybbuPE3y8q68YkO10eg9j3FR4uWazlvI1C8FEmK0SCdQjzX/VK/GmGPJJxzpU/5L8oSuQo+q3FDzQ/sl5RtAtQxuIbh+Qo5ccUkZyXkhb8ery9j5UqxgqmyTnhKTQB2g7ImiKQ8+dPSKvWHrc7n/0Kgols2rpJERFVp4E/StrKCWNafoYU7AQECUzIJqxu8+UWq85DokoL7Bep+dH3l+JtE9dAtZmskwUg629MFiHK3sLAsXG8FVVdBqOEOKW8kGs2/wVQt9zQLxMLyRtKi+Z2cihvXKmGnefa43lXmQuAYNBneZ2oeq0lNK3E5bjLWL/sBzrr2+0dgvM7R7TPgBJBb/f9Y2HjVCIMMAg49rs05PAxFtNbzpfmHz2f419y7HJ2pa0ICKMq6P+gcXmSElOxLtd4uYxC5bOrVqVT0VAYZtN1WvAT/Wnaysvc8plJPj42WgHXxZyH2ms2tCLQmh54WZyF3Swk+C2ksUNSj90oM=
  api_key:
    secure: HsHEGoCw2z8suCfN6RrrhzbYEFQJ5fGYMi+gGgXAH7zi/mpXhB/uS9AF3gldq2oTH8O8YmBP6Wych8wjOXVq3IGwxDX0vJIxiouKKly8TiFF/y/xb7NGRuPIJjzLqmsEXpJysV3OrReqDDWXhrRYHDZctdlDVbmmLu42RPbUbkGis8k9adbzBCzupN/d8mn7Jub1CRys13EMjYh1O7WOMq4E7Fq9lNgEjH5ifbV8CW6qDf550f5oneYOi7GT5KXhEBQNwqZaeTNlbcfuyiK7vb5eh4PVlqm9Wl6slfkiIvIAvIfGqoMOV0DUB2mCRxhzCxrlLi4tcGZFth9nwq4dzhY4b0HtqWbbmrMqyhAu0MjqnMfIVCGt81+dBLs6tvSnFx6l421UHHPlxa3cTV/VkTJgd1Fij73DqGIJANjniIgvBeY07fO5oCNYbeMouWfvf9yoLDh8Gh2kkSheNV3aqaBb6Sr9+ncXnVC5LwIZmHkog2BWnpQiTXIFnzWiue0xX79WwdjVnGgE4NQvFn5sUkGdQTSMl9RPxQmOGhoRG8OAiMJEfR6tlAn8FsBxCHMNg/Vgr0ZbYKyU1Er2q2G6LD4tQPqxUvHqCLu+FFdvWh5cB/WOiC9+5/dWHR0eOyQwyj8yOJyRfLcUBaJTcWMfVvd0KrClJu/50wUOzyJigpQ=
  skip_cleanup: true
