language: node_js

os:
  - linux
  - osx

node_js:
  - 4
  - 6
  - stable

env:
  # BITCLOCK_TOKEN
  secure: MIWUBVs9HY7PN6HYHKstapslfXsf4CRJ0f3KJSkK8rQ9sSnXGJDwXki6wpqe82WU3afeCoVk+WSDk603xhwxuc1EDfcaXiUULnPmvAZqGIRv/iE7Jwy2+O+qpUrJv3s0SPQb5bOs8QkvA8Ud/gT68xmXeEi+TjJ9J2aoJwQQ67GRBca7HKw7dTe4jSChCssDj50+kN8oUuTjyUND1lg413rCKtK0xL1+qugBmAkc894DpMvDcYJYUNNaUOenLmDxQgaBWLWOTxv600gVxOkt1yrxY02wZEA/aaq5anG0FBEgAx+uSsElG2sckeA5XHHSDM64Y5bjqeO54Vuw2zDljoW/qzP+yQVVkaHLbNZBWv2pjigAJnMnMqEyKVLuwv6mOGBueG0A6kL5S/OFSQ/9ZnnTsib61qMtm0wxRLRtdN1PkOcIvqOWhQ0VrwfCiUZptjyjKPSQtirmvW7NEunEKwiWOTb2xlksFOHzylb/ABhXYyWmSpqhtAqcvhMV4qvUZiZ2ePOY7lRjvh9XKtoqCo5SrJkxuQHVZCLDtuZZ55oarBihCB0CAKyDz4L96jvFytI0u/qTxcDwK3M4LtpYnI6DUxVPvODNrKYMNgd6kdYvJ56XATxb1icin24VNAgOPI2En/IrmH8U+VzlZnxPb3AVnUWMJyjt49en2FSiafw=

deploy:
  provider: npm
  on:
    tags: true
  email:
    secure: U5Yibbm/JWAVD6qlVDr2wC3Lkmax6gkh27jLt5ReaXpr/M656dr34/hv0/Wd2kfUSPuVvneDw/2HyhIQ5plz8l9rkikG+HQVipqP9S16rCq7eyg/vyhHlL7DZv44P673e715upHAtxxcQPjevixHZIgSGkDJtAY/JudJb78AzV39dpABftB7YPNHlz7O87D0K8jerglZ9kctOwPJPfdf0jycDyfOnP6s3Nh2otWPgA2TLNe402nXalP7/BlgIMstNNNcG6Xwiy4Rxl21pijaIpsuD/F+lIyNufYg/5sUx6CFdwfYp3N5JhuXFWQ409BK4hZoEVYvXfUP3wjCB9lrlCWpfri5oNFdOOvazG5DuvGn0bF7maAYN9PwJYtQZa2uFjlBGEeY4LJLlHK0GFAYP5+0TRelbQA7dU5z29+2NDNh0jOKkomhV9o5cRfeuHsg2PaWg+uHlmEMPzHLavtl2u8DIt2BbR0gtnbSqd+PjBfSbeFBOOYTSNWvXxqtEhtm+Ve93soJkVHgxbji3UTtWDGqJ/zfJwdMlHroXOsmpENcNzARMxw+TM3Twx89mWVepZ0uG8+KmHm8rmLxNyHzFfd3QC24F9M29YMBOiAwL1Y22FTdX0QZ0NtumOX6rI9qdTjpF6pjHbvnzSvcSmmqMJwj+YNqnDq3UM0XyydAQqI=
  api_key:
    secure: o1wjvNvXfw4mDXU/6/T9qnrVZ06CdsJUE3hVNZ+1doUfL5Vd/Y7hIeh80AO9o2d1MojueAnxiDmfGH4AjwEIwqkcxf+8HjzQvlDtP/GrIbzSOBu4TGTV7EoQvrMtmb1w5B2QZd0xJZoXMn/BIzq5b46k5iyHdFyEtLf9+G6aRL5LSWorgFOSMP8KUlWZTsclaf7TSXB4OmTqntuRwz9EHViX7VDRTztsJduKUR/mwtEAjss9DyKXpR46nGnNzE7iJwtatgyJi/mf2tWOB+hE61N4Bd3q61yONaePjHFQA5UvP32GOoR53uIWnYHuJrHO/D5/DoTlkbqXb5hSGC1c+RHpTYRC8FLJLuNd1Tna3SUFnvr9nuPiW3FF17Ih1F+6UKc3q39bFesj3v1nz2CgmXuDHlqn6mchIXEMTRsMjnYLexMIrS7TkWwKQtzytNFbCisGijdVhpR8G9vdzUeo/54k6/6hCbozHlyiac6S9Qgec4mMTB8AMDJXeha1fkG5z8eWyuGwFnEL1yNApcRZ9gKEfZgnApJXz6tWTVpwLRRXG51AqSxiz/Kc4uHsukCmJdcaBq/Us2971a7S9//axvenKJZ+qkEWVj8I0mEcaPZCcN5SPMlOSURgNiteUuTOI8ie7NOT7GVyH1LsyOWi0drRRtfEboKn91FWBfflXR8=
  skip_cleanup: true
